create review branch
Mahamadou-Nouridine/microverser-html-css-challenge pull request #1
Opened 2023-03-27 16:21 UTC by Mahamadou-Nouridine

in this PR i've done these tasks:

- create a new branch for the Pr
- added a new line in order to have difference with last commit

2023-03-30 17:13 UTC, Mahamadou-Nouridine reviewed
# Changes required ♻️ 

Please check my comment below and make all the required changes

Submit for a re-review when you're done

thanks  :)

2023-03-30 17:13 UTC, Mahamadou-Nouridine commented on index.html
Please do not leave more than one empty line between HTML elements. Many newlines make the code not clean

2023-03-30 17:31 UTC, TadesseDev requested changes
### Hi @Mahamadou-Nouridine 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
- [x] Good job using inline comments.
 
## Required Changes ♻️
- [ ] Dear @Mahamadou-Nouridine, I like your review, but we need to have no less than two review comments on the project `Please wrote at least 2 comments in the review.`. I can see you have only one. Please consider making a re-review with two comments.
_Check the comments under the review._

## Optional suggestions
- [Optional] Please consider adding an emoji/gif to your review summary. This will make your review more friendly.
- [Optional] Please also try to summarize your review in more detail. Remember this is where you give a general summary of your review. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 08:19 UTC, Mahamadou-Nouridine commented on README.md
> +# 📖 [Title] <a name="about-project"></a>
Please use your project title instead of the default title, because the repository title can not to be the

2023-03-31 08:19 UTC, Mahamadou-Nouridine commented on README.md
> +### Tech Stack <a name="tech-stack"></a>
Please Make sure to include the tech stack used to build the project

2023-03-31 08:19 UTC, Mahamadou-Nouridine commented on index.html
> +</div> -->
Please don't leave unused code in the code base, this makes the code not clean and long

2023-03-31 08:29 UTC, Mahamadou-Nouridine reviewed
STATUS: REQUIRED CHANGES ♻️♻️

Hi @Mahamadou-Nouridine 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f632e74656e6f722e636f6d2f764f4c575f55514d79534941414141432f616c6d6f73742d74686572652e676966](https://user-images.githubusercontent.com/98597449/229066995-b7ff3d7f-a4a5-46f1-828b-0e3dbf3f7c82.gif)

# To highlight 🍾

- Good commit history ✔️
- Your design looks good 💯 ✔️
- Good PR description ✔️
- Follow GitHub flow ✔️

2023-03-31 08:56 UTC, GedeonTS commented
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @Mahamadou-Nouridine ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- Good job using GitHub review feature :+1: 
- Polite and clear suggestions :+1: 
- Good use of inline comments :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 09:23 UTC, merged